spring:
  datasource:
    url: jdbc:mysql://bab-db-cluster.cluster-c9sw3jhfgxq7.ap-south-1.rds.amazonaws.com:3306/jobplanner_dev
    username: admin
    password: bab$$g$TB$ILLING&32
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
        show-sql: true
        ejb:
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  
